name: build

on:
  pull_request: {}
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Validate before checking out submodules which have their own wrappers.
      - uses: gradle/wrapper-validation-action@v1

      - run: git submodule update --init

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: ./gradlew build
